---
 - name: play for conditions on facts
   hosts: accenture
   tasks:
           - name: Install mysql server
             dnf:
                name: mysql
                state: present
             become: yes
             user: userA
             when: ansible_memfree_mb >= 250

